---
title: "R Notebook"
output: html_notebook
---

```{r setup, echo = F, message = F}
library(jsonlite)
library(dplyr)
library(ggplot2)
library(stringr)
library(ggthemes)
library(scales)
# Globals ---- 

API_KEY = readLines("../apikey.txt", warn = F) # Namara.io API key
DATA_SET_ID_F  = "5149f141-b653-4e91-86f9-14e7f33e7830"
DATA_SET_ID_M = "b0eeaeb2-bf54-4de6-8a0f-d2fda674284b"

URL_M = paste0("http://api.namara.io/v0/data_sets/", 
             DATA_SET_ID_M, "/data/en-4?api_key=", API_KEY)

URL_F = paste0("http://api.namara.io/v0/data_sets/", 
               DATA_SET_ID_F, "/data/en-4?api_key=", API_KEY)

# Cache dataset
RDS = "../rds/baby_names.rds" 

# Functions ----
get_api_data <- function(URL, max = 1e06, verbose = TRUE) {
  cat("\nGrabbing data from Namara: ")
  df <- data.frame()
  for (i in seq(0,250*1e06, by = 250)) {
    offset_url = paste0(URL, "&offset=", i)
    tmp <- fromJSON(readLines(offset_url, warn = F))
    if (verbose & i %% 1000 == 0) cat(".")
    if (length(tmp) == 0) break
    df <- rbind(df, tmp)
  }
  df
}

add_freq <- function(df) {
  df %>% 
    group_by(year) %>% 
    mutate(percents = frequency / sum(frequency)) %>% 
    arrange(name, year) %>% 
    group_by(name) %>% 
    mutate(rel_risk = percents / lag(percents),
           rel_loss = (1 - round(rel_risk,2)) * 100) %>% 
    mutate(ends_1 = str_sub(name, -1, -1),
           ends_2 = str_sub(name, -2, -1),
           ends_3 = str_sub(name, -3, -1),
           name_length = nchar(name))
}

plot_single_name <- function(df, name_match) {
  x <- subset(df, df$name == name_match)
  ggplot(x, aes_q(quote(year), quote(percents), colour = quote(sex))) + 
    geom_line() +
    scale_y_continuous(labels=percent) 
}

filter_name <- function(df, name_match) {
  subset(df, df$name == name_match)
}

gs <- function(fn) {
  ggsave(fn, dpi = 96, width = 12.271, height = 8.75)
}

# Import data ----

if(!file.exists(RDS)) {
  male_names <- get_api_data(URL_M)
  female_names <- get_api_data(URL_F)
  save(male_names, female_names, file = RDS)
} else load(RDS)

mn <- add_freq(male_names)
fn <- add_freq(female_names)
mn$sex = "male"
fn$sex = "female"
an <- rbind(mn, fn)

# Create table of ending letters
last_letter <- an %>% 
  group_by(sex, year, ends_1) %>% 
  summarise(freq = sum(frequency), n = n()) %>% 
  group_by(sex, year) %>% 
  mutate(percents = freq / sum(freq))

color = case_when(
  last_letter$ends_1 == "E" ~ "E",
  last_letter$ends_1 == "A" ~ "A",
  last_letter$ends_1 == "N" ~ "N",
  TRUE ~ "Other")

last_letter$color = color

# Create decade table
an$decade <- cut(an$year, breaks = seq(1901,2021,10), 
                 include.lowest = TRUE, right = F, 
                 labels = seq(1900,2010,10))
decade <- an %>% 
  group_by(sex, decade, name) %>% 
  summarise(frequency = sum(frequency)) %>% 
  group_by(sex, decade) %>% 
  mutate(percents = frequency / sum(frequency))

top_decade <- decade %>% 
  group_by(sex, decade) %>% 
  top_n(1, wt = percents) %>% 
  mutate(adj = ifelse(sex == 'male', 1, -1))


# Plots
ggthemr('light', layout = "clear", spacing = 1.5, text_size = 12)
```

```{r}
# Last letter trend
ggplot(last_letter, aes(year, percents, color = color, group = ends_1)) + 
  geom_line() +
  facet_wrap(~ sex) +
  scale_color_manual(values = c("#F8766D", "#7CAE00", "#00BFC4", "#BBBBBB")) +
  scale_y_continuous(labels=percent) +
  labs(y = "Occurence of Name", color = "Last Letter in Name", title = "Last Letter Trends for Males and Female Ontario-Born Babies") +
  theme(legend.position = "bottom", 
        panel.grid = element_line(),
        panel.grid.major.y = element_line(color = 'grey70'),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())
gs("../img/male_female_base.png")
```

```{r}
# Top Frequency by Decade
ggplot(top_decade, aes(decade, percents, group = sex, colour = sex)) +
  geom_line() + 
  scale_y_continuous(labels=percent) +
  labs(y="% of Names", x = "Decade", 
       title = "Proportion of Top Name as % of Total Population by Decade/Sex") +
  geom_text(aes(label = str_to_title(name), y = percents  + (0.006 * adj )), nudge_x = 0.2, size =3)
gs("../img/top_name_decade.png")

```


```{r}
# Name length
nlq <- an %>% 
  group_by(sex,year) %>% 
  summarise(avg = mean(name_length), 
            sd = sd(name_length))

ggplot(data=nlq, aes(year, colour = sex)) + 
  geom_line(aes(y = avg)) +
  labs(x = "Year", y = "Avg. Name Length")
gs("../img/avg_name_length.png")
```


```{r}
# Vowel counter

vowels <- an %>% 
  group_by(sex, year) %>% 
  mutate(v_cnt = str_count(name, "[AEIOUY]"),
         v_freq = v_cnt / name_length) %>% 
  group_by(sex, year) %>% 
  mutate(weighted_cnt = v_cnt * percents,
            weighted_freq = v_freq * percents) %>% 
  summarise(wcnt = sum(weighted_cnt),
            wfrq = sum(weighted_freq))

ggplot(data=vowels, aes(year, wfrq, colour = sex)) + 
  geom_line() + 
  labs(x="Year", y = "Frequency of Vowels in Name", title = "Rise of the Vowels
Proportion of names that are made of vowels (incl. Y)") +
  scale_y_continuous(labels=percent)
gs("../img/rise_of_vowels.png")
```

```{r}
# First Letter
first_letter <- an %>% 
  mutate(first_letter = str_sub(name, 1, 1)) %>% 
  group_by(sex, year, first_letter) %>% 
  summarise(freq = sum(frequency)) %>% 
  group_by(sex, year) %>% 
  mutate(percents = freq / sum(freq))

fl_plot <- first_letter %>% 
  filter(first_letter %in% c('A', 'E', 'I'))

ggplot(fl_plot, aes(year, percents, colour = first_letter)) + 
  geom_line() + 
  facet_wrap( ~ sex) +
  scale_y_continuous(labels=percent) + 
  labs(color = "First Letter of Name", title = "Race to the top of the roll call")
gs("../img/first_letter_name.png")
```

```{r}
# K and C
kc <- an %>% 
  mutate(has_k = str_detect(name, 'K') * frequency, 
         has_c = str_detect(name, 'C') * frequency) %>% 
  group_by(sex, year) %>% 
  summarise(has_k = sum(has_k),
            has_c = sum(has_c),
            total = sum(frequency)) %>% 
  mutate(has_k  = has_k / total,
         has_c = has_c / total)

ggplot(data=filter(kc, sex == 'female'), aes(year)) + 
  geom_line(aes(y=has_k, colour = "Has K")) + 
  geom_line(aes(y=has_c, colour = "Has C")) +
  scale_x_continuous(limits = c(1940,2010))
```

```{r}
double_vowels <- an %>% 
  mutate(has_aa = str_detect(name, 'AA') * frequency, 
         has_ee = str_detect(name, 'EE') * frequency,
         has_oo = str_detect(name, 'OO') * frequency) %>% 
  group_by(sex, year) %>% 
  summarise(has_aa = sum(has_aa),
            has_ee = sum(has_ee),
            has_oo = sum(has_oo),
            total = sum(frequency)) %>% 
  mutate(has_aa = has_aa / total,
         has_ee = has_ee / total,
         has_oo = has_oo / total)

ggplot(data=double_vowels, aes(year)) + 
  geom_line(aes(y=has_aa, colour = "Has AA")) + 
  geom_line(aes(y=has_ee, colour = "Has EE")) +
  geom_line(aes(y=has_oo, colour = "Has OO")) +
  facet_wrap(~ sex, nrow = 1) + 
  labs(y = "Proportion of Names",
       title = "Rise of the AA/EE/OOs\nDouble Vowels in Names") +
  scale_y_continuous(labels=percent)
gs("../img/double_vowels.png")
```

